baseurl = "http://www.hcbravo.org/networks-across-scales/"
languageCode = "en-us"
title = "CMSC828O: Networks Across Scales (Fall 2018)"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Héctor Corrada Bravo"
	description = "Analysis tools for biological networks across scales (COMBINE NRT course), Department of Computer Science, University of Maryland"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/hcorrada/networks-across-scales.git"

	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["mathjax.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "light-blue"
    	accent  = "orange"

 [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"

 [params.links]
      elms   = "https://umd.instructure.com/courses/1247019"
      piazza = "https://piazza.com/class/jldiw9ttj5223l"

[social]
	twitter = "hcorrada"
	github  = "hcorrada"

[[menu.main]]
  name = "Calendar"
  url  = "calendar/"
  weight = 5

[[menu.main]]
	name   = "Logistics"
	url    = "logistics/"
	weight = 10

#[[menu.main]]
	#name   = "Resources"
	#url    = "resources/"
	#weight = 30

[[menu.main]]
	name   = "Projects"
	url    = "projects/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
